apiVersion: apps/v1
kind: Deployment
metadata:
  name: history
spec:
  replicas: 1
  selector:
    matchLabels:
      app: history
  template:
    metadata:
      labels:
        app: history
    spec:
      containers:
      - name: history
        image: pjbear/history
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: video-streaming-config
        env:
        - name: DBHOST
          value: "mongodb://mongo:3000"
        - name: DBNAME
          value: "history"

---
apiVersion: v1
kind: Service
metadata:
  name: history
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: history

