apiVersion: v1
kind: ConfigMap
metadata:
  name: video-streaming-config
data:
  PORT: "80"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-streaming
  template:
    metadata:
      labels:
        app: video-streaming
    spec:
      containers:
      - name: video-streaming
        image: pjbear/video-streaming
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: video-streaming-config

---
apiVersion: v1
kind: Service
metadata:
  name: video-streaming
spec:
  type: LoadBalancer
  ports:
  - port: 3001
    targetPort: 80
  selector:
    app: video-streaming
